import React, { createContext, useContext, useState } from 'react';

export type SupportedLanguage = 'en' | 'hi' | 'mr' | 'ta' | 'bn';

export interface LanguageInfo {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
];

const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    appName: 'SahakariSeva',
    appTagline: 'Cooperative Household & Community Services',
    verifiedBadge: 'Verified Cooperative Member',
    portalCustomer: 'Customer Portal',
    portalWorker: 'Worker (Employee) Portal',
    portalAdmin: 'Cooperative Admin',
    switchPortal: 'Switch Portal',
    needServiceToday: 'What service do you need today?',
    emergencyAssistance: 'Emergency Assistance (Within 30 Mins)',
    emergencySubtitle: 'Burst pipes, power loss, lockouts & urgent repairs',
    bookNow: 'Book Now',
    requestService: 'Request Service',
    allCategories: 'Service Domains',
    plumbing: 'Plumbing',
    electrical: 'Electrical Work',
    carpentry: 'Carpentry',
    painting: 'Painting',
    cleaning: 'Deep Cleaning',
    appliance: 'Appliance Repair',
    gardening: 'Gardening & Lawns',
    driving: 'Driver & Chauffeur',
    caregiving: 'Elder & Patient Care',
    myBookings: 'My Bookings',
    noActiveBookings: 'No active bookings currently.',
    problemDescription: 'Describe the problem (or tap mic to speak)',
    uploadPhotos: 'Add Photos/Videos (Optional)',
    serviceAddress: 'Service Address',
    scheduleTime: 'Preferred Schedule',
    immediate: 'Immediate / Urgent',
    scheduled: 'Schedule Slot',
    transparentBill: 'Transparent Cooperative Bill Breakdown',
    workerEarningsShare: 'Direct Worker Payout (88%)',
    cooperativeWelfare: 'Worker Welfare & Health Fund (7%)',
    platformMaintenance: 'Society Operations & Tech (5%)',
    commercialComparison: 'Compared to commercial apps (30% cut), 95% stays with the worker & cooperative!',
    payNow: 'Confirm & Pay',
    workerAssigned: 'Assigned Cooperative Worker',
    jobStatus: 'Status',
    statusRequested: 'Request Submitted',
    statusMatched: 'Matched to Verified Society Worker',
    statusAccepted: 'Worker Accepted & En Route',
    statusInProgress: 'Service in Progress',
    statusCompleted: 'Work Completed',
    rateService: 'Rate & Cooperative Feedback',
    voiceAssistant: 'Voice Assistant Active',
    voiceAssistantHelp: 'Speak in your preferred language to request a service',
    
    // Worker Portal
    workerWelcome: 'Welcome, Brother / Sister',
    cooperativeId: 'Cooperative ID',
    activeSociety: 'Affiliated Society',
    todaysEarnings: 'Today\'s Earnings',
    monthEarnings: 'Month Payout',
    welfareFundAccrued: 'Welfare & Dividend Fund',
    insuranceActive: 'Group Accidental Insurance: Active',
    newJobRequests: 'Nearby Cooperative Job Requests',
    fairAllocationScore: 'Fair Allocation Priority: HIGH',
    fairAllocationDesc: 'Prioritized to guarantee fair income across society members',
    acceptJob: 'Accept Job (हाँ, स्वीकार करें)',
    declineJob: 'Pass to Society Peer',
    startJob: 'Start Job at Location',
    completeJob: 'Complete Job & Upload Proof',
    jobDetails: 'Job Details',
    customerLocation: 'Customer Address',
    customerLanguage: 'Customer Speaks',
    translateChatMessage: 'Translate into my language',
    listenToInstructions: 'Listen (Audio Narration)',

    // Admin Portal
    adminFederationOverview: 'Cooperative Federation Overview',
    totalVerifiedWorkers: 'Active Verified Workers',
    activeJobsCount: 'Ongoing Community Jobs',
    welfareDisbursed: 'Welfare Distributed',
    fairAllocationIndex: 'Fair Allocation Equity Index',
    workerVerificationDesk: 'Worker Onboarding & KYC Desk',
    pendingVerification: 'Pending Review',
    approveWorker: 'Approve & Issue Society ID',
    rejectWorker: 'Reject with Feedback',
    viewDocuments: 'View Aadhaar & Skill Certificates',
    societyFundLedger: 'Federation Welfare Fund Ledger',
  },
  hi: {
    appName: 'सहकारी सेवा',
    appTagline: 'सहकारी घरेलू एवं सामुदायिक सेवा मंच',
    verifiedBadge: 'प्रमाणित सहकारी सदस्य',
    portalCustomer: 'ग्राहक पोर्टल',
    portalWorker: 'श्रमिक (कर्मचारी) पोर्टल',
    portalAdmin: 'सहकारी प्रशासक',
    switchPortal: 'पोर्टल बदलें',
    needServiceToday: 'आज आपको किस सेवा की आवश्यकता है?',
    emergencyAssistance: 'आपातकालीन सहायता (30 मिनट में)',
    emergencySubtitle: 'पाइप फटना, बिजली गुल, लॉक टूटना या जरूरी मरम्मत',
    bookNow: 'अभी बुक करें',
    requestService: 'सेवा का अनुरोध करें',
    allCategories: 'सेवा श्रेणियां',
    plumbing: 'प्लंबिंग (नलसाजी)',
    electrical: 'इलेक्ट्रिकल (बिजली कार्य)',
    carpentry: 'बढ़ईगीरी (कारपेंटर)',
    painting: 'पेंटिंग व रंगाई',
    cleaning: 'गहरी सफाई (क्लीनिंग)',
    appliance: 'उपकरण मरम्मत',
    gardening: 'बागवानी व हरियाली',
    driving: 'चालक / ड्राइवर',
    caregiving: 'बुजुर्ग एवं देखभाल सेवा',
    myBookings: 'मेरी बुकिंग्स',
    noActiveBookings: 'वर्तमान में कोई सक्रिय बुकिंग नहीं है।',
    problemDescription: 'समस्या बताएं (या बोलने के लिए माइक छुएं)',
    uploadPhotos: 'फोटो/वीडियो जोड़ें (वैकल्पिक)',
    serviceAddress: 'सेवा का पता',
    scheduleTime: 'समय चुनें',
    immediate: 'तत्काल / आपातकालीन',
    scheduled: 'समय तय करें',
    transparentBill: 'पारदर्शी सहकारी बिल विवरण',
    workerEarningsShare: 'श्रमिक का सीधा भुगतान (88%)',
    cooperativeWelfare: 'श्रमिक कल्याण एवं स्वास्थ्य कोष (7%)',
    platformMaintenance: 'सहकारी संचालन एवं तकनीक (5%)',
    commercialComparison: 'निजी कंपनियों (30% कमीशन) के मुकाबले, 95% पैसा सीधे श्रमिक और सहकारी कोष में जाता है!',
    payNow: 'पुष्टि करें और भुगतान करें',
    workerAssigned: 'नियुक्त सहकारी श्रमिक',
    jobStatus: 'स्थिति',
    statusRequested: 'अनुरोध दर्ज किया गया',
    statusMatched: 'प्रमाणित सहकारी श्रमिक से मिलान',
    statusAccepted: 'श्रमिक ने स्वीकार किया, रास्ते में है',
    statusInProgress: 'काम प्रगति पर है',
    statusCompleted: 'काम पूरा हो गया',
    rateService: 'रेटिंग व सहकारी फीडबैक',
    voiceAssistant: 'वॉयस असिस्टेंट सक्रिय',
    voiceAssistantHelp: 'सेवा बुक करने के लिए अपनी पसंदीदा भाषा में बोलें',
    
    // Worker Portal
    workerWelcome: 'स्वागत है, साथी',
    cooperativeId: 'सहकारी सदस्य संख्या',
    activeSociety: 'संबद्ध सहकारी समिति',
    todaysEarnings: 'आज की कमाई',
    monthEarnings: 'इस महीने की कमाई',
    welfareFundAccrued: 'कल्याण व लाभांश कोष',
    insuranceActive: 'सामूहिक दुर्घटना बीमा: सक्रिय',
    newJobRequests: 'निकटवर्ती नए काम के अनुरोध',
    fairAllocationScore: 'समान अवसर प्राथमिकता: उच्च',
    fairAllocationDesc: 'सभी सहकारी सदस्यों को बराबर कमाई का अवसर सुनिश्चित करने हेतु प्राथमिकता',
    acceptJob: 'हाँ, काम स्वीकार करें',
    declineJob: 'साथी श्रमिक को सौंपें',
    startJob: 'पहुंचकर काम शुरू करें',
    completeJob: 'काम पूरा करें व फोटो जोड़ें',
    jobDetails: 'कार्य विवरण',
    customerLocation: 'ग्राहक का पता',
    customerLanguage: 'ग्राहक की भाषा',
    translateChatMessage: 'मेरी भाषा में अनुवाद करें',
    listenToInstructions: 'सुनें (आवाज में निर्देश)',

    // Admin Portal
    adminFederationOverview: 'सहकारी महासंघ समीक्षा',
    totalVerifiedWorkers: 'सक्रिय सत्यापित श्रमिक',
    activeJobsCount: 'प्रगतिरत सामुदायिक कार्य',
    welfareDisbursed: 'वितरित कल्याणकारी सहायता',
    fairAllocationIndex: 'अवसर समानता सूचकांक',
    workerVerificationDesk: 'श्रमिक सत्यापन व केवाईसी डेस्क',
    pendingVerification: 'सत्यापन हेतु लंबित',
    approveWorker: 'स्वीकृत करें व आईडी जारी करें',
    rejectWorker: 'कारण सहित अस्वीकृत करें',
    viewDocuments: 'आधार व कौशल प्रमाणपत्र जांचें',
    societyFundLedger: 'महासंघ कल्याण कोष बहीखाता',
  },
  mr: {
    appName: 'सहकारी सेवा',
    appTagline: 'सहकारी घरगुती व समुदाय सेवा मंच',
    verifiedBadge: 'प्रमाणित सहकारी सदस्य',
    portalCustomer: 'ग्राहक पोर्टल',
    portalWorker: 'कामगार (कर्मचारी) पोर्टल',
    portalAdmin: 'सहकारी प्रशासक',
    switchPortal: 'पोर्टल बदला',
    needServiceToday: 'आज आपल्याला कोणत्या सेवेची गरज आहे?',
    emergencyAssistance: 'तातडीची मदत (३० मिनिटांत)',
    emergencySubtitle: 'पाईप फुटणे, वीज जाणे, कुलूप तोडणे व तातडीची कामे',
    bookNow: 'आता बुक करा',
    requestService: 'सेवेची विनंती करा',
    allCategories: 'सेवा प्रकार',
    plumbing: 'प्लंबिंग (नलकारी)',
    electrical: 'इलेक्ट्रिकल (विद्युत काम)',
    carpentry: 'सुतारकाम (कारपेंटर)',
    painting: 'रंगकाम',
    cleaning: 'सखोल स्वच्छता',
    appliance: 'उपकरण दुरुस्ती',
    gardening: 'बागकाम',
    driving: 'वाहन चालक (ड्रायव्हर)',
    caregiving: 'रुग्ण व ज्येष्ठ नागरिक सेवा',
    myBookings: 'माझ्या बुकिंग्स',
    noActiveBookings: 'सध्या कोणतीही सक्रिय बुकिंग नाही.',
    problemDescription: 'समस्या सांगा (किंवा बोलण्यासाठी माइक दाबा)',
    uploadPhotos: 'फोटो/व्हिडिओ जोडा (ऐच्छिक)',
    serviceAddress: 'सेवेचा पत्ता',
    scheduleTime: 'वेळ निवडा',
    immediate: 'तातडीने',
    scheduled: 'वेळ ठरवून',
    transparentBill: 'पारदर्शक सहकारी बिल तपशील',
    workerEarningsShare: 'कामगाराचा थेट वाटा (८८%)',
    cooperativeWelfare: 'कामगार कल्याण व आरोग्य निधी (७%)',
    platformMaintenance: 'सहकारी संस्था व तंत्रज्ञान खर्च (५%)',
    commercialComparison: 'खाजगी कंपन्यांच्या ३०% कमिशनच्या तुलनेत, ९५% उत्पन्न कामगार व सहकारी निधीकडे जाते!',
    payNow: 'पुष्टी करा व पैसे भरा',
    workerAssigned: 'नेमलेला सहकारी कामगार',
    jobStatus: 'स्थिती',
    statusRequested: 'विनंती नोंदवली',
    statusMatched: 'प्रमाणित कामगार जुळवला',
    statusAccepted: 'कामगाराने स्वीकारले, निघत आहेत',
    statusInProgress: 'काम सुरू आहे',
    statusCompleted: 'काम पूर्ण झाले',
    rateService: 'अभिप्राय व रेटिंग',
    voiceAssistant: 'व्हॉइस असिस्टंट चालू',
    voiceAssistantHelp: 'सेवा मागवण्यासाठी तुमच्या भाषेत बोला',
    
    // Worker Portal
    workerWelcome: 'स्वागत आहे, सहकारी मित्र',
    cooperativeId: 'सहकारी सदस्य क्र.',
    activeSociety: 'संलग्न सहकारी संस्था',
    todaysEarnings: 'आजची कमाई',
    monthEarnings: 'या महिन्याची कमाई',
    welfareFundAccrued: 'कल्याण व लाभांश निधी',
    insuranceActive: 'सामूहिक विमा: सक्रिय',
    newJobRequests: 'जवळपास उपलब्ध नवीन कामे',
    fairAllocationScore: 'समान वाटप प्राधान्य: उच्च',
    fairAllocationDesc: 'सर्व सभासदांना समान उत्पन्नाची संधी देण्यासाठी प्राधान्य',
    acceptJob: 'होय, काम स्वीकारा',
    declineJob: 'इतर सहकाऱ्यास द्या',
    startJob: 'कामास सुरुवात करा',
    completeJob: 'काम पूर्ण करा व फोटो काढा',
    jobDetails: 'कामाचा तपशील',
    customerLocation: 'ग्राहकाचा पत्ता',
    customerLanguage: 'ग्राहकाची भाषा',
    translateChatMessage: 'माझ्या भाषेत अनुवाद करा',
    listenToInstructions: 'ऐका (ध्वनी संदेश)',

    // Admin Portal
    adminFederationOverview: 'सहकारी महासंघ आढावा',
    totalVerifiedWorkers: 'सक्रिय प्रमाणित कामगार',
    activeJobsCount: 'सुरू असलेली कामे',
    welfareDisbursed: 'वितरित कल्याण निधी',
    fairAllocationIndex: 'समान संधी निर्देशांक',
    workerVerificationDesk: 'कामगार पडताळणी डेस्क',
    pendingVerification: 'पडताळणीसाठी प्रलंबित',
    approveWorker: 'मान्यता द्या व ओळखपत्र द्या',
    rejectWorker: 'कारणासह नाकारा',
    viewDocuments: 'कागदपत्रे तपासा',
    societyFundLedger: 'महासंघ निधी हिशोब',
  },
  ta: {
    appName: 'சஹகாரி சேவா',
    appTagline: 'கூட்டுறவு வீட்டு மற்றும் சமூக சேவை தளம்',
    verifiedBadge: 'சரிபார்க்கப்பட்ட கூட்டுறவு உறுப்பினர்',
    portalCustomer: 'வாடிக்கையாளர் தளம்',
    portalWorker: 'தொழிலாளர் தளம்',
    portalAdmin: 'கூட்டுறவு நிர்வாகி',
    switchPortal: 'தளத்தை மாற்றுக',
    needServiceToday: 'இன்று உங்களுக்கு என்ன சேவை தேவை?',
    emergencyAssistance: 'அவசர உதவி (30 நிமிடங்களில்)',
    emergencySubtitle: 'குழாய் உடைப்பு, மின் வெட்டு, பூட்டு பழுது',
    bookNow: 'இப்போதே பதிவு செய்',
    requestService: 'சேவை கோருக',
    allCategories: 'சேவை பிரிவுகள்',
    plumbing: 'குழாய் பழுது (பிளம்பிங்)',
    electrical: 'மின்சார வேலை',
    carpentry: 'மரவேலை (தச்சர்)',
    painting: 'வண்ணப்பூச்சு',
    cleaning: 'முழு தூய்மைப்பணி',
    appliance: 'மின்சாதன பழுது',
    gardening: 'தோட்டப்பணி',
    driving: 'ஓட்டுநர் பணி',
    caregiving: 'முதியோர் பராமரிப்பு',
    myBookings: 'எனது பதிவுகள்',
    noActiveBookings: 'தற்போது பதிவுகள் இல்லை.',
    problemDescription: 'பிரச்சனையை விவரிக்கவும் (அல்லது பேசவும்)',
    uploadPhotos: 'புகைப்படங்கள் இணைக்கவும்',
    serviceAddress: 'சேவை முகவரி',
    scheduleTime: 'நேரத்தை தேர்ந்தெடுக்கவும்',
    immediate: 'உடனடி உதவி',
    scheduled: 'நேரம் திட்டமிடப்பட்டது',
    transparentBill: 'வெளிப்படையான கூட்டுறவு கட்டண விவரம்',
    workerEarningsShare: 'தொழிலாளியின் நேரடி வருவாய் (88%)',
    cooperativeWelfare: 'தொழிலாளர் நல நிதி (7%)',
    platformMaintenance: 'கூட்டுறவு பராமரிப்பு (5%)',
    commercialComparison: 'தனியார் தளங்களின் 30% கமிஷனுடன் ஒப்பிடும்போது, 95% தொழிலாளர் & நல நிதிக்கே செல்கிறது!',
    payNow: 'உறுதி செய்து பணம் செலுத்துக',
    workerAssigned: 'ஒதுக்கப்பட்ட கூட்டுறவு தொழிலாளி',
    jobStatus: 'நிலை',
    statusRequested: 'கோரிக்கை சமர்ப்பிக்கப்பட்டது',
    statusMatched: 'தொழிலாளி ஒதுக்கப்பட்டார்',
    statusAccepted: 'ஏற்கப்பட்டது, வந்து கொண்டிருக்கிறார்',
    statusInProgress: 'பணி நடக்கிறது',
    statusCompleted: 'பணி முடிந்தது',
    rateService: 'மதிப்பீடு மற்றும் கருத்து',
    voiceAssistant: 'குரல் உதவி இயக்கத்தில் உள்ளது',
    voiceAssistantHelp: 'சேவை பெற உங்கள் மொழியில் பேசவும்',

    // Worker Portal
    workerWelcome: 'வணக்கம், கூட்டுறவு தோழரே',
    cooperativeId: 'கூட்டுறவு எண்',
    activeSociety: 'இணைந்த சங்கம்',
    todaysEarnings: 'இன்றைய வருமானம்',
    monthEarnings: 'மாத வருவாய்',
    welfareFundAccrued: 'நல நிதி இருப்பு',
    insuranceActive: 'குழு காப்பீடு: செயலில் உள்ளது',
    newJobRequests: 'அருகிலுள்ள புதிய வேலைகள்',
    fairAllocationScore: 'சம வாய்ப்பு முன்னுரிமை: அதிகம்',
    fairAllocationDesc: 'அனைத்து உறுப்பினர்களுக்கும் சம வருவாயை உறுதி செய்ய முன்னுரிமை',
    acceptJob: 'வேலையை ஏற்றுக்கொள்',
    declineJob: 'மற்றொரு தோழருக்கு மாற்று',
    startJob: 'வேலையைத் தொடங்கு',
    completeJob: 'வேலையை முடி & படம் பதிவேற்று',
    jobDetails: 'வேலை விவரங்கள்',
    customerLocation: 'வாடிக்கையாளர் முகவரி',
    customerLanguage: 'வாடிக்கையாளர் மொழி',
    translateChatMessage: 'என் மொழியில் மொழிபெயர்',
    listenToInstructions: 'கேட்க (குரல் வழிகாட்டி)',

    // Admin Portal
    adminFederationOverview: 'கூட்டுறவு கூட்டமைப்பு கண்ணோட்டம்',
    totalVerifiedWorkers: 'செயலில் உள்ள தொழிலாளர்கள்',
    activeJobsCount: 'நடைபெறும் பணிகள்',
    welfareDisbursed: 'வழங்கப்பட்ட நலத்திட்ட நிதி',
    fairAllocationIndex: 'சமத்துவ பகிர்வு குறியீடு',
    workerVerificationDesk: 'சரிபார்ப்பு மேசை',
    pendingVerification: 'சரிபார்ப்புக்கு காத்திருப்பவை',
    approveWorker: 'ஒப்புதல் அளித்து அடையாள அட்டை வழங்குக',
    rejectWorker: 'நிராகரி',
    viewDocuments: 'ஆவணங்களை சரிபார்',
    societyFundLedger: 'நல நிதி பதிவேடு',
  },
  bn: {
    appName: 'সমবায় সেবা',
    appTagline: 'সমবায় মালিকানাধীন গৃহস্থালি ও নাগরিক পরিষেবা মঞ্চ',
    verifiedBadge: 'যাচাইকৃত সমবায় সদস্য',
    portalCustomer: 'গ্রাহক পোর্টাল',
    portalWorker: 'শ্রমিক (কর্মী) পোর্টাল',
    portalAdmin: 'সমবায় প্রশাসক',
    switchPortal: 'পোর্টাল পরিবর্তন',
    needServiceToday: 'আজ আপনার কোন সেবা প্রয়োজন?',
    emergencyAssistance: 'জরুরি সহায়তা (৩০ মিনিটে)',
    emergencySubtitle: 'পাইপ ফাটা, বিদ্যুৎ বিভ্রাট ও জরুরি মেরামত',
    bookNow: 'এখনই বুক করুন',
    requestService: 'সেবার আবেদন করুন',
    allCategories: 'সেবা বিভাগসমূহ',
    plumbing: 'প্লাম্বিং (নল মেরামত)',
    electrical: 'ইলেকট্রিক্যাল কাজ',
    carpentry: 'ছুতোরের কাজ',
    painting: 'রংমিস্ত্রি',
    cleaning: 'গভীর পরিচ্ছন্নতা',
    appliance: 'যন্ত্রপাতি মেরামত',
    gardening: 'বাগান পরিচর্যা',
    driving: 'গাড়ি চালক',
    caregiving: 'বয়স্ক ও রোগীর সেবা',
    myBookings: 'আমার বুকিং',
    noActiveBookings: 'বর্তমানে কোনো সক্রিয় বুকিং নেই।',
    problemDescription: 'সমস্যার বিবরণ দিন (বা কথা বলতে মাইকে চাপুন)',
    uploadPhotos: 'ছবি/ভিডিও যোগ করুন (ঐচ্ছিক)',
    serviceAddress: 'সেবার ঠিকানা',
    scheduleTime: 'সময় নির্ধারণ',
    immediate: 'জরুরি সেবা',
    scheduled: 'সময় সূচি অনুযায়ী',
    transparentBill: 'স্বচ্ছ সমবায় বিল বিবরণী',
    workerEarningsShare: 'শ্রমিকের সরাসরি পারিশ্রমিক (৮৮%)',
    cooperativeWelfare: 'শ্রমিক কল্যাণ ও স্বাস্থ্য তহবিল (৭%)',
    platformMaintenance: 'সমবায় পরিচালনা ও প্রযুক্তি (৫%)',
    commercialComparison: 'ব্যক্তিগত অ্যাপের ৩০% কমিশনের তুলনায়, ৯৫% সরাসরি শ্রমিক ও সমবায়ে থাকে!',
    payNow: 'নিশ্চিত করুন ও পেমেন্ট দিন',
    workerAssigned: 'নিযুক্ত সমবায় কর্মী',
    jobStatus: 'অবস্থা',
    statusRequested: 'অনুরোধ জমা পড়েছে',
    statusMatched: 'কর্মী নির্ধারিত হয়েছে',
    statusAccepted: 'কর্মী গ্রহণ করেছেন, রওনা হয়েছেন',
    statusInProgress: 'কাজ চলছে',
    statusCompleted: 'কাজ সম্পন্ন হয়েছে',
    rateService: 'রেটিং ও সমবায় মতামত',
    voiceAssistant: 'ভয়েস সহকারী সক্রিয়',
    voiceAssistantHelp: 'সেবা নিতে আপনার নিজের ভাষায় বলুন',

    // Worker Portal
    workerWelcome: 'স্বাগতম, সমবায় কর্মী বন্ধু',
    cooperativeId: 'সমবায় সদস্য নং',
    activeSociety: 'অনুমোদিত সমবায় সমিতি',
    todaysEarnings: 'আজকের আয়',
    monthEarnings: 'মাসিক আয়',
    welfareFundAccrued: 'কল্যাণ ও লভ্যাংশ তহবিল',
    insuranceActive: 'গ্রুপ দুর্ঘটনা বীমা: সক্রিয়',
    newJobRequests: 'কাছাকাছি নতুন কাজের সুযোগ',
    fairAllocationScore: 'ন্যায্য সুযোগ অগ্রাধিকার: উচ্চ',
    fairAllocationDesc: 'সকল সমবায় সদস্যের সম-আয়ের লক্ষ্যে অগ্রাধিকার',
    acceptJob: 'কাজটি গ্রহণ করুন',
    declineJob: 'অন্য সঙ্গীকে হস্তান্তর করুন',
    startJob: 'কাজ শুরু করুন',
    completeJob: 'কাজ সম্পন্ন করুন ও ছবি তুলুন',
    jobDetails: 'কাজের বিবরণ',
    customerLocation: 'গ্রাহকের ঠিকানা',
    customerLanguage: 'গ্রাহকের ভাষা',
    translateChatMessage: 'আমার ভাষায় অনুবাদ করুন',
    listenToInstructions: 'শুনুন (ভয়েস নির্দেশিকা)',

    // Admin Portal
    adminFederationOverview: 'সমবায় ফেডারেশন সামগ্রিক চিত্র',
    totalVerifiedWorkers: 'সক্রিয় যাচাইকৃত কর্মী',
    activeJobsCount: 'চলমান সেবা কাজ',
    welfareDisbursed: 'বিতরণকৃত কল্যাণ তহবিল',
    fairAllocationIndex: 'সুযোগ সমতা সূচক',
    workerVerificationDesk: 'কর্মী যাচাই ও কেওয়াইসি ডেস্ক',
    pendingVerification: 'যাচাইয়ের অপেক্ষায়',
    approveWorker: 'অনুমোদন দিন ও কার্ড ইস্যু করুন',
    rejectWorker: 'প্রত্যাখ্যান করুন',
    viewDocuments: 'কাগজপত্র পরীক্ষা করুন',
    societyFundLedger: 'কল্যাণ তহবিল খতিয়ান',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  isTranslating: boolean;
  translateText: (text: string, targetLang?: SupportedLanguage) => Promise<string>;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
  isTranslating: false,
  translateText: async (text: string) => text,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<SupportedLanguage>('en');
  const [isTranslating, setIsTranslating] = useState<boolean>(false);

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  const translateText = async (text: string, targetLang?: SupportedLanguage): Promise<string> => {
    const target = targetLang || language;
    if (target === 'en' && language === 'en') return text;
    setIsTranslating(true);
    try {
      // Call backend language-service if available, fallback with simulated bilingual output
      const response = await fetch('http://localhost:3005/language/translate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text,
          targetLanguage: target,
          context: 'cooperative household gig service',
        }),
      });
      if (response.ok) {
        const data = await response.json();
        return data.translatedText || text;
      }
    } catch {
      // Fallback gracefully
    } finally {
      setIsTranslating(false);
    }
    return `[${target.toUpperCase()}] ${text}`;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isTranslating, translateText }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
